export const mockEmployees = [
  {
    id: "1",
    name: "Sarah Johnson",
    employeeId: "EMP001",
    position: "Frontend Developer",
    department: "Engineering",
    email: "sarah.johnson@example.com",
    phone: "+1 (555) 123-4567",
    joinDate: "May 1, 2023",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    birthDate: "April 15, 1990",
    address: "123 Main St, San Francisco, CA 94105",
    emergencyContact: "John Johnson, +1 (555) 987-6543",
    bloodGroup: "O+",
    employeeType: "Full-time",
    manager: "David Wilson",
    workLocation: "San Francisco Office",
    salary: "$95,000",
    skills: ["React", "TypeScript", "CSS", "HTML", "JavaScript"],
    education: [
      {
        degree: "Bachelor of Science in Computer Science",
        institution: "Stanford University",
        year: "2012",
      },
      {
        degree: "Master of Science in Web Development",
        institution: "UC Berkeley",
        year: "2014",
      },
    ],
    documents: [
      {
        name: "Resume.pdf",
        uploadDate: "May 1, 2023",
      },
      {
        name: "Contract.pdf",
        uploadDate: "May 1, 2023",
      },
      {
        name: "ID.jpg",
        uploadDate: "May 1, 2023",
      },
    ],
    reviews: [
      {
        title: "Annual Performance Review",
        rating: 4.5,
        comments: "Sarah has been an exceptional team member, consistently delivering high-quality work.",
        reviewer: "David Wilson",
        date: "April 1, 2023",
      },
      {
        title: "Project Evaluation",
        rating: 4.8,
        comments: "Outstanding contribution to the website redesign project.",
        reviewer: "Emily Davis",
        date: "February 15, 2023",
      },
    ],
    achievements: [
      {
        title: "Employee of the Month",
        description: "Recognized for outstanding performance and dedication.",
        date: "March 2023",
      },
      {
        title: "Project Excellence Award",
        description: "For exceptional contribution to the mobile app launch.",
        date: "January 2023",
      },
    ],
  },
  {
    id: "2",
    name: "Michael Brown",
    employeeId: "EMP002",
    position: "Marketing Specialist",
    department: "Marketing",
    email: "michael.brown@example.com",
    phone: "+1 (555) 234-5678",
    joinDate: "April 15, 2023",
    status: "On Leave",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "3",
    name: "Emily Davis",
    employeeId: "EMP003",
    position: "HR Manager",
    department: "Human Resources",
    email: "emily.davis@example.com",
    phone: "+1 (555) 345-6789",
    joinDate: "April 10, 2023",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "4",
    name: "David Wilson",
    employeeId: "EMP004",
    position: "Backend Developer",
    department: "Engineering",
    email: "david.wilson@example.com",
    phone: "+1 (555) 456-7890",
    joinDate: "April 5, 2023",
    status: "Remote",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "5",
    name: "Jessica Taylor",
    employeeId: "EMP005",
    position: "UX Designer",
    department: "Engineering",
    email: "jessica.taylor@example.com",
    phone: "+1 (555) 567-8901",
    joinDate: "March 20, 2023",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "6",
    name: "Robert Martinez",
    employeeId: "EMP006",
    position: "Financial Analyst",
    department: "Finance",
    email: "robert.martinez@example.com",
    phone: "+1 (555) 678-9012",
    joinDate: "March 15, 2023",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "7",
    name: "Jennifer Garcia",
    employeeId: "EMP007",
    position: "Sales Representative",
    department: "Sales",
    email: "jennifer.garcia@example.com",
    phone: "+1 (555) 789-0123",
    joinDate: "March 10, 2023",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "8",
    name: "Christopher Lee",
    employeeId: "EMP008",
    position: "Operations Manager",
    department: "Operations",
    email: "christopher.lee@example.com",
    phone: "+1 (555) 890-1234",
    joinDate: "March 5, 2023",
    status: "On Leave",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "9",
    name: "Amanda White",
    employeeId: "EMP009",
    position: "Content Writer",
    department: "Marketing",
    email: "amanda.white@example.com",
    phone: "+1 (555) 901-2345",
    joinDate: "February 25, 2023",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "10",
    name: "Daniel Harris",
    employeeId: "EMP010",
    position: "DevOps Engineer",
    department: "Engineering",
    email: "daniel.harris@example.com",
    phone: "+1 (555) 012-3456",
    joinDate: "February 20, 2023",
    status: "Remote",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const mockAttendance = [
  {
    id: "1",
    employeeId: "EMP001",
    employeeName: "Sarah Johnson",
    date: "May 1, 2023",
    checkIn: "09:00 AM",
    checkOut: "06:00 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "2",
    employeeId: "EMP002",
    employeeName: "Michael Brown",
    date: "May 1, 2023",
    checkIn: "09:30 AM",
    checkOut: "05:30 PM",
    checkInStatus: "late",
    checkOutStatus: "on-time",
    workingHours: "8.0",
    status: "Present",
  },
  {
    id: "3",
    employeeId: "EMP003",
    employeeName: "Emily Davis",
    date: "May 1, 2023",
    checkIn: "08:45 AM",
    checkOut: "05:45 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "4",
    employeeId: "EMP004",
    employeeName: "David Wilson",
    date: "May 1, 2023",
    checkIn: "09:15 AM",
    checkOut: "04:30 PM",
    checkInStatus: "on-time",
    checkOutStatus: "early",
    workingHours: "7.25",
    status: "Present",
  },
  {
    id: "5",
    employeeId: "EMP005",
    employeeName: "Jessica Taylor",
    date: "May 1, 2023",
    checkIn: "",
    checkOut: "",
    checkInStatus: "",
    checkOutStatus: "",
    workingHours: "0",
    status: "Absent",
  },
  {
    id: "6",
    employeeId: "EMP001",
    employeeName: "Sarah Johnson",
    date: "April 30, 2023",
    checkIn: "08:55 AM",
    checkOut: "06:05 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.17",
    status: "Present",
  },
  {
    id: "7",
    employeeId: "EMP002",
    employeeName: "Michael Brown",
    date: "April 30, 2023",
    checkIn: "09:00 AM",
    checkOut: "01:00 PM",
    checkInStatus: "on-time",
    checkOutStatus: "early",
    workingHours: "4.0",
    status: "Half Day",
  },
  {
    id: "8",
    employeeId: "EMP003",
    employeeName: "Emily Davis",
    date: "April 30, 2023",
    checkIn: "08:50 AM",
    checkOut: "05:50 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "9",
    employeeId: "EMP004",
    employeeName: "David Wilson",
    date: "April 30, 2023",
    checkIn: "09:10 AM",
    checkOut: "06:10 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "10",
    employeeId: "EMP005",
    employeeName: "Jessica Taylor",
    date: "April 30, 2023",
    checkIn: "09:05 AM",
    checkOut: "06:00 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "8.92",
    status: "Present",
  },
]

export const mockLeaveRequests = [
  {
    id: "1",
    employeeId: "EMP001",
    employeeName: "Sarah Johnson",
    leaveType: "Vacation",
    startDate: "May 10, 2023",
    endDate: "May 15, 2023",
    days: 6,
    reason: "Family vacation",
    status: "Pending",
  },
  {
    id: "2",
    employeeId: "EMP002",
    employeeName: "Michael Brown",
    leaveType: "Sick Leave",
    startDate: "May 3, 2023",
    endDate: "May 4, 2023",
    days: 2,
    reason: "Not feeling well",
    status: "Approved",
  },
  {
    id: "3",
    employeeId: "EMP003",
    employeeName: "Emily Davis",
    leaveType: "Personal",
    startDate: "May 8, 2023",
    endDate: "May 8, 2023",
    days: 1,
    reason: "Personal appointment",
    status: "Approved",
  },
  {
    id: "4",
    employeeId: "EMP004",
    employeeName: "David Wilson",
    leaveType: "Vacation",
    startDate: "May 20, 2023",
    endDate: "May 27, 2023",
    days: 8,
    reason: "Summer vacation",
    status: "Pending",
  },
  {
    id: "5",
    employeeId: "EMP005",
    employeeName: "Jessica Taylor",
    leaveType: "Unpaid Leave",
    startDate: "May 15, 2023",
    endDate: "May 19, 2023",
    days: 5,
    reason: "Family emergency",
    status: "Rejected",
  },
  {
    id: "6",
    employeeId: "EMP006",
    employeeName: "Robert Martinez",
    leaveType: "Sick Leave",
    startDate: "May 5, 2023",
    endDate: "May 5, 2023",
    days: 1,
    reason: "Doctor's appointment",
    status: "Approved",
  },
  {
    id: "7",
    employeeId: "EMP007",
    employeeName: "Jennifer Garcia",
    leaveType: "Personal",
    startDate: "May 12, 2023",
    endDate: "May 12, 2023",
    days: 1,
    reason: "Personal reasons",
    status: "Pending",
  },
  {
    id: "8",
    employeeId: "EMP008",
    employeeName: "Christopher Lee",
    leaveType: "Vacation",
    startDate: "May 1, 2023",
    endDate: "May 5, 2023",
    days: 5,
    reason: "Spring break",
    status: "Approved",
  },
  {
    id: "9",
    employeeId: "EMP009",
    employeeName: "Amanda White",
    leaveType: "Sick Leave",
    startDate: "May 2, 2023",
    endDate: "May 3, 2023",
    days: 2,
    reason: "Feeling unwell",
    status: "Approved",
  },
  {
    id: "10",
    employeeId: "EMP010",
    employeeName: "Daniel Harris",
    leaveType: "Personal",
    startDate: "May 18, 2023",
    endDate: "May 19, 2023",
    days: 2,
    reason: "Family event",
    status: "Pending",
  },
]

export const mockProjects = [
  {
    id: "1",
    name: "Website Redesign",
    client: "Acme Corporation",
    startDate: "April 1, 2023",
    deadline: "June 30, 2023",
    team: ["Sarah Johnson", "David Wilson", "Jessica Taylor"],
    progress: 65,
    status: "In Progress",
  },
  {
    id: "2",
    name: "Mobile App Development",
    client: "TechStart Inc.",
    startDate: "March 15, 2023",
    deadline: "July 15, 2023",
    team: ["David Wilson", "Daniel Harris"],
    progress: 40,
    status: "In Progress",
  },
  {
    id: "3",
    name: "Marketing Campaign",
    client: "GreenLife Products",
    startDate: "April 10, 2023",
    deadline: "May 10, 2023",
    team: ["Michael Brown", "Amanda White", "Jennifer Garcia"],
    progress: 85,
    status: "In Progress",
  },
  {
    id: "4",
    name: "HR System Implementation",
    client: "Internal",
    startDate: "February 1, 2023",
    deadline: "April 30, 2023",
    team: ["Emily Davis", "Christopher Lee"],
    progress: 100,
    status: "Completed",
  },
  {
    id: "5",
    name: "Financial Reporting Tool",
    client: "Global Finance Ltd.",
    startDate: "March 1, 2023",
    deadline: "May 31, 2023",
    team: ["Robert Martinez", "Sarah Johnson"],
    progress: 75,
    status: "In Progress",
  },
  {
    id: "6",
    name: "E-commerce Platform",
    client: "ShopEasy",
    startDate: "January 15, 2023",
    deadline: "April 15, 2023",
    team: ["Sarah Johnson", "David Wilson", "Jessica Taylor", "Daniel Harris"],
    progress: 100,
    status: "Completed",
  },
  {
    id: "7",
    name: "CRM Integration",
    client: "SalesForce Pro",
    startDate: "April 5, 2023",
    deadline: "June 5, 2023",
    team: ["Jennifer Garcia", "Michael Brown"],
    progress: 30,
    status: "In Progress",
  },
  {
    id: "8",
    name: "Data Migration",
    client: "DataSafe Inc.",
    startDate: "March 20, 2023",
    deadline: "May 20, 2023",
    team: ["Daniel Harris", "David Wilson"],
    progress: 50,
    status: "On Hold",
  },
  {
    id: "9",
    name: "Social Media Strategy",
    client: "BrandBoost",
    startDate: "April 15, 2023",
    deadline: "May 15, 2023",
    team: ["Amanda White", "Michael Brown"],
    progress: 60,
    status: "In Progress",
  },
  {
    id: "10",
    name: "Office Relocation",
    client: "Internal",
    startDate: "February 15, 2023",
    deadline: "March 31, 2023",
    team: ["Christopher Lee", "Emily Davis", "Robert Martinez"],
    progress: 100,
    status: "Completed",
  },
]
